application: appbfw #bunjilfw #appbfw #application: appbfw #bunjilfw
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- admin_redirect: on
- appstats: on
- deferred: on
- remote_api: off

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*/notused/.*$
- ^(.*/)?.*/build/.*$
- ^(.*/)?.*/source/.*$
- ^(.*/)?.*\.db$

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: webob
  version: latest
- name: ssl
  version: latest
- name: pycrypto
  version: latest
- name: webapp2
  version: latest
- name: django
  version: "1.5"

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /login/google
  script: main.app
  login: required
  secure: always

- url: /obs/*
  script: main.app
  login: optional
  secure: always
  
- url: /admin/.*
  script: main.app
  login: admin

- url: /tasks/.*
  script: main.app

- url: /.*
  script: main.app
  secure: always
  